server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: Treasured-Book
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: MySQLInDocker
    schema: classpath:database/schema.sql
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    root: info
